# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/fubalapp-new-tournament-service
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "5c:56:41:0f:75:af:71:de:f7:6b:ab:e6:55:eb:64:26"
            - "64:1e:84:ab:1a:2e:b6:7a:25:46:ab:82:23:a7:ab:13
"
      - run:
          name: Get dependencies
          command: go get ./...
      - run:
          name: Build
          command: go build -o new-tournament -i ./cmd/run
      - run:
          name: Add host to known hosts
          command: ssh-keyscan $SSH_HOST >> $HOME/.ssh/known_hosts
      - run:
          name: Move binary file
          command: |
            scp server $SSH_USER@$SSH_HOST:/home/ubuntu/fubalapp